# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20170523_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
